// lang.js - 英文詞庫 (English)
window.uiText = window.uiText || {};
window.uiText['en'] = { 
    title: "HK Smart Price", 
    ogTitle: 'HK Smart Price | HK Gov Price Watch',
    ogDesc: 'HK Smart Price Watch. Find the best deals instantly!',
    badge: "Live Gov Data", 
    subLabel: "Fetching update time...", 
    lastUpdated: "Updated: ",
    mainCat: "Step 1: Select Category", 
    sortTip: "Frequent First", 
    back: "Back", 
    loading: "Syncing live prices...", 
    error: "Failed to load", 
    send: "Search", 
    placeholder: "Type product, brand or keywords...", 
    notFound: "Not found! 🤖 But I found some related suggestions for you:",
    suggestBrand: "Or try this brand:",
    suggestCategory: "You might be looking for this category:",
    backToSearch: "Search Again",
    searchAnyway: "Search anyway: {keyword}",
    lblUpdatePrefix: 'Updated: ',
    
    chatWelcome: "Got it! You've selected", 
    chatAsk: "What product or brand are you looking for?", 
    chatFound: "Here are the best prices we found for you:", 
    chatShowAll: "Here is the full list of products in this category:", 
    chatNoResult: "Oops, we couldn't find any matching products! 🤔 Try using shorter or different keywords.",

    alertModalTitle: "Set Price Alert",
    alertModalCurrentPrice: "Current lowest price: ",
    alertModalTargetPrompt: "Remind me when the price drops below (HK$):",
    alertModalPrivacy: "Privacy Guarantee: This feature uses offline processing. Your watchlist is saved locally on your device and no personal data is collected.",
    alertModalBtn: "Add to Watchlist",
    alertInvalidPrice: "Please enter a valid target price!",
    alertListTitle: "My Watchlist",
    alertListEmpty: "<span class='text-3xl block mb-2'>📭</span>Your watchlist is empty.<br>Click 🔔 on a product card to add!",
    alertListHit: "Target Reached! Now",
    alertListCurrent: "Current:",
    alertListTarget: "Target:",
    alertListClose: "Close",
    
    ocrSuccess: "✅ Recognition complete! Please confirm the keyword before searching.",
    ocrError: "⚠️ Cannot recognize the text. Please try taking a clearer picture!",

    ocrSuccessGemini: "🎯 Gemini recognition complete! Please verify the keyword and search.",
    ocrSuccessBasic: "✅ Recognition complete! Please verify the keyword and search.",
    ocrFailGemini: "⚠️ Gemini couldn't recognize the product. Please aim at the packaging and try again!",
    ocrFailBasic: "⚠️ AI couldn't recognize the product. Please aim at the brand name and try again!",
    ocrErrorGemini: "Gemini connection failed. Check your API Key! Falling back to basic mode.",
    ocrErrorBasic: "OCR engine failed to start! Please check your network or try again later.",

    ocrModalTitle: "📷 AI Visual Recognition",
    ocrLoadingGemini: "Summoning Gemini AI Vision...",
    ocrLoadingBasic: "Starting basic AI engine...",
    ocrProgress: "Recognizing packaging text...",
    ocrLoadingLang: "Loading AI language data...",

    cameraModalTitle: "📸 AI Visual Recognition",
    cameraBtn: "📷 Take Photo or Choose Image",
    advSettings: "Advanced Settings",
    geminiTitle: "⚙️ Connect Gemini Pro",
    geminiDesc: "Default uses basic offline recognition. Enter a Google Gemini API Key to significantly improve accuracy for complex packaging. (Safely stored locally)",
    geminiPlaceholder: "API Key (AIzaSy...)",
    saveBtn: "Save",
    clearBtn: "Clear",
    statusConnected: "✅ Connected to Gemini Pro",
    statusOffline: "🐢 Using basic offline engine",
    alertKeySaved: "✅ Key saved securely!",
    alertKeyCleared: "🗑️ Key cleared. Returning to basic mode.",
    cameraTooltip: "AI Vision Settings",
    geminiGuide: "👉 Click here to get your free Google API Key",

    quickAll: "📦 Show All",
    quickDiscount: "🏷️ Discounted Only",
    quickHome: "🏠 Main Menu",
    quickBye: "👋 Goodbye",
    
    miniFooterLinks: "About, Terms & Disclaimer",
    miniFooterCopy: "© 2026 HK Smart Price",
    disclaimerTitle: "Disclaimer & Terms of Service",
    
    disclaimerText: `<strong>1. Data Source & IP Rights:</strong><br>Price and promotional data in this app are sourced from the "Online Price Watch" dataset on Data.gov.hk. All intellectual property rights belong to the <strong>Consumer Council</strong> and respective merchants.<br><br>
    <strong>2. Data Coverage:</strong><br>The dataset mainly covers thousands of popular daily essentials selected by the Consumer Council and does not include all supermarket inventory (such as exclusive or niche items).<br><br>
    <strong>3. Automated Calculation:</strong><br>The calculated average prices displayed are <strong>automatically generated by the system</strong>. All information is based on the latest live data released by the government and final tags in physical stores. For reference only; users are advised to verify prices before purchasing.<br><br>
    <strong>4. Site Technology & Ad Disclosure:</strong><br>This site uses Google Analytics to analyze traffic and Google AdSense to display advertisements. These services may collect anonymous user data via cookies. By continuing to use this site, you agree to our use of cookies.<br><br>
    <strong>5. Limitation of Liability:</strong><br>This app is provided on an "AS IS" basis. Users assume all risks. The application and its developer shall not be held legally liable for any loss or damage arising from price differences, data delays, or reliance on the information provided.`,

    modalBtn: 'I Understand & Accept',

    footerAbout: "About Us",
    footerContact: "Contact Us",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service",
    footerDevTeam: "Developed by: ",
    footerDevName: "Lazy Tools Station",
    
    aboutTitle: "About HK Smart Price🔎",
    aboutContent: "HK Smart Price🔎 aims to provide a convenient price comparison platform for Hong Kong citizens.<br><br>Say goodbye to downloading and filtering complex government Excel sheets! With our AI-powered search app, you can effortlessly compare prices and find the best discounts across supermarkets in seconds.",
    contactTitle: "Contact Us",
    contactContent: "For inquiries or collaborations, please feel free to reach out.<br><br>(Contact info coming soon!)",
    privacyTitle: "Privacy Policy",
    privacyContent: "We value your privacy. This application does not collect any sensitive personal data or browsing history.",
    termsTitle: "Terms of Service",
    termsContent: "All price and promotional data are directly sourced from the official 'Data.gov.hk' dataset provided by the Hong Kong Government. The calculated average prices are automatically generated by the system. All information is based on the latest daily data released by the government.",

    shareAppTitle: "Share with Friends!",
    shareAppDesc: "Scan the QR Code below or copy the link to share the savings with your friends and family!",
    shareBtnCopy: "Copy Link",
    shareBtnWhatsApp: "WhatsApp",
    shareBtnMore: "More Options",
    copiedToast: "✅ Link copied to clipboard!",
    shareMessage: "Check out the HK Smart Price Tracker🔎! Compare supermarket prices instantly and save money! 🛒\n",
    shareProductTitle: "HK Smart Price 🔎 Recommendation",
    shareProductTemplate: "[Hot Deal] {brand} - {name}, lowest price at ${price}! Check it out on HK Smart Price 🔎! 🛒",

    globalTitle: "Global Catalog Search",
    modeStart: "Starting '{label}' mode 🌍<br>Searching now...",
    globalStart: "Got it! Starting 'Global Catalog Search' mode 🌍<br>Let me find it for you.",
    askKeyword: "What product are you looking for? Try typing 'Cola' or 'Noodles'.",

    foundBigGapKw: 'Here are the top deals for "{keyword}" with huge price gaps:',
    foundBigGapCat: 'Here are the top deals with huge price gaps in this category:',
    foundDiscountKw: 'Here are the discounted products for "{keyword}":',
    foundDiscountCat: 'Here are the discounted products in this category:',
    foundKw: 'Here are the best results for "{keyword}":',

    appTitle: "SmartDeal Board", pageTitleText: "SmartDeal Board", subTitleText: "Compare with City Average",
    filterPlace: "Search category, brand, product or store...", backBtn: "Back",
    optSmAll: "Best Store (All)", optCatAll: "All Categories", optSortDiff: "📉 Highest True Discount", optSortMinP: "💰 Lowest Price", optSortCustom: "Custom Sort",
    qsLabel: "Quick Search:", qs1: "Cola", qs2: "Noodles", qs3: "PARKnSHOP", qs4: "Wellcome",
    listTitle: "🔥 Today's Top Discounts", dailyUpdateBadge: "Daily Update",
    thRank: "Rank", thCat: "Category", thSm: "Store", thBrand: "Brand", thName: "Product Name", thType: "Offer Type", thOrig: "Original", thEff: "Effective", thDiff: "True Diff", thOther: "Other Prices",
    typeDiscount: "📉 True Drop", typePromo: "🏷️ Promo Offer", noData: "No Data Found 🤷‍♂️", origPriceStr: "Orig.", fail: "Load Failed",


   mcTitle: "Lowest Price Tracker",
    mcSub: "Dynamic Sorting | Independent Categories | 1-Click Reset",
    mcDropCard: "📉 True Drop",
    mcDropDesc: "Lowest, actual drop ≤ -1%",
    mcFlatCard: "🛡️ Price Moat",
    mcFlatDesc: "Lowest, unchanged (±1%)",
    mcUpCard: "📈 Price Hike",
    mcUpDesc: "Lowest, actual hike ≥ 1%",
    mcSmChart: "🏪 Supermarket Force",
    mcCatChart: "🛒 Top 10 Categories",
    mcSearchPlace: "Search product, brand or category...",
    mcBtnReset: "🧹 Reset Filters",
    mcInfoBtn: "Metrics & Disclaimer",
    
    mcPillAll: "👑 All Records",
    mcPillDrop: "📉 True Drop",
    mcPillFlat: "🛡️ Price Moat",
    mcPillUp: "📈 Price Hike",
    mcOptAllSt: "👑 All Strategies",
    mcOptDrop: "📉 True Drop",
    mcOptFlat: "🛡️ Price Moat",
    mcOptUp: "📈 Price Hike",
    
    mcClickToFilter: "Double-click to filter",
    mcFilteredSm: "Filtered Store: ",
    mcFilteredCat: "Filtered Category: ",
    mcClickToCancel: "(Click chart blank space to cancel)",
    mcShow: "Showing ",
    mcItem: " to ",
    mcTotal: " items, Total ",
    mcLoading: "Calculating Price Data...",
    mcNoData: "No Records Found",
    mcAvgBase: "Market Avg",
    mcDev: "Deviation",
    mcRealDrop: "Real Drop",
    
    // 全新競爭大前提聲明
    mcModalTitle: "ℹ️ Metrics & Disclaimer",
    mcModalBtn: "I Understand",
    mcModalContent: `<p class="mb-4 text-[13px] text-slate-600 dark:text-slate-300">The primary purpose of this dashboard is to track and present products that have successfully defeated all market competitors to secure the absolute "Lowest Price" (Winner-take-all) status in the city. As long as a product wins the cross-merchant price comparison, it will be listed here regardless of whether its own price has increased, decreased, or remained unchanged. The system further analyzes the historical price fluctuations of these winners, categorizing them into four strategic dimensions:</p>
                     <ul class="space-y-4">
                        <li class="flex gap-3"><span class="shrink-0 text-2xl">👑</span><div><b class="text-slate-700 dark:text-slate-200">All Records:</b><br><span class="text-slate-500 dark:text-slate-400 text-xs">The total volume of products currently holding the absolute lowest price after winning cross-merchant competition.</span></div></li>
                        <li class="flex gap-3"><span class="shrink-0 text-2xl">📉</span><div><b class="text-teal-700 dark:text-teal-400">True Drop Items:</b><br><span class="text-slate-500 dark:text-slate-400 text-xs">Among the winners, these products have recorded a genuine price decrease (≤ -1%) compared to their own historical records.</span></div></li>
                        <li class="flex gap-3"><span class="shrink-0 text-2xl">🛡️</span><div><b class="text-slate-600 dark:text-slate-300">Price Moat (Unchanged):</b><br><span class="text-slate-500 dark:text-slate-400 text-xs">Among the winners, these products maintain a stable price (fluctuations within ±1%), holding the baseline against competitors.</span></div></li>
                        <li class="flex gap-3"><span class="shrink-0 text-2xl">📈</span><div><b class="text-red-700 dark:text-red-400">Price Hike Items:</b><br><span class="text-slate-500 dark:text-slate-400 text-xs">Among the winners, these products remain the cheapest available option in the market, but have actually increased in price (≥ 1%) compared to their own historical baseline.</span></div></li>
                     </ul>
                     <p class="mt-4 pt-3 border-t border-slate-100 dark:border-slate-700 text-xs text-slate-400">Declaration: For details regarding the underlying data collision and price normalization algorithms, please refer to the official declaration in the 【True Discount Report】.</p>`

                    };

window.supermarketDict = window.supermarketDict || {};
window.supermarketDict['en'] = { 
    'WELLCOME': 'Wellcome', 
    'PARKNSHOP': 'PARKnSHOP', 
    'JASONS': 'Market Place (Jasons)',
    'MARKETPLACE': 'Market Place (Jasons)', 
    'AEON': 'AEON', 
    'WATSONS': 'Watsons', 
    'MANNINGS': 'Mannings', 
    'USELECT': 'U-Select', 
    'LUNGFUNG': 'Lung Fung',
    'DCHFOOD': 'DCH Food Mart',
    'SASA': 'Sa Sa'
};

// 安全掛載：全域共用之超市樣式字典
window.supermarketStyleDict = window.supermarketStyleDict || {
    'WELLCOME': {
        indexCard: 'border-red-200 bg-red-50/30 dark:border-red-900/50 dark:bg-red-900/20',
        indexText: 'text-red-700 dark:text-red-400',
        badgeBg: 'bg-red-50 dark:bg-red-900/20',
        badgeText: 'text-red-600 dark:text-red-400',
        badgeBorder: 'border-red-200 dark:border-red-800',
        battleBg: 'bg-red-50 dark:bg-red-900/20',
        battleBorder: 'border-red-100 dark:border-red-800/50',
        battleText: 'text-red-700 dark:text-red-400',
        battleCountBg: 'bg-red-600 text-white border-transparent'
    },
    'LUNGFUNG': {
        indexCard: 'border-red-200 bg-red-50/30 dark:border-red-900/50 dark:bg-red-900/20',
        indexText: 'text-red-700 dark:text-red-400',
        badgeBg: 'bg-red-50 dark:bg-red-900/20',
        badgeText: 'text-red-600 dark:text-red-400',
        badgeBorder: 'border-red-200 dark:border-red-800',
        battleBg: 'bg-red-50 dark:bg-red-900/20',
        battleBorder: 'border-red-100 dark:border-red-800/50',
        battleText: 'text-red-700 dark:text-red-400',
        battleCountBg: 'bg-red-600 text-white border-transparent'
    },
    'PARKNSHOP': {
        indexCard: 'border-blue-200 bg-blue-50/30 dark:border-blue-900/50 dark:bg-blue-900/20',
        indexText: 'text-blue-700 dark:text-blue-400',
        badgeBg: 'bg-blue-50 dark:bg-blue-900/20',
        badgeText: 'text-blue-600 dark:text-blue-400',
        badgeBorder: 'border-blue-200 dark:border-blue-800',
        battleBg: 'bg-blue-50 dark:bg-blue-900/20',
        battleBorder: 'border-blue-100 dark:border-blue-800/50',
        battleText: 'text-blue-700 dark:text-blue-400',
        battleCountBg: 'bg-blue-600 text-white border-transparent'
    },
    'WATSONS': {
        indexCard: 'border-teal-200 bg-teal-50/30 dark:border-teal-900/50 dark:bg-teal-900/20',
        indexText: 'text-teal-700 dark:text-teal-400',
        badgeBg: 'bg-teal-50 dark:bg-teal-900/20',
        badgeText: 'text-teal-600 dark:text-teal-400',
        badgeBorder: 'border-teal-200 dark:border-teal-800',
        battleBg: 'bg-teal-50 dark:bg-teal-900/20',
        battleBorder: 'border-teal-100 dark:border-teal-800/50',
        battleText: 'text-teal-700 dark:text-teal-400',
        battleCountBg: 'bg-teal-600 text-white border-transparent'
    },
    'HKTVMALL': {
        indexCard: 'border-green-200 bg-green-50/30 dark:border-green-900/50 dark:bg-green-900/20',
        indexText: 'text-green-700 dark:text-green-400',
        badgeBg: 'bg-green-50 dark:bg-green-900/20',
        badgeText: 'text-green-600 dark:text-green-400',
        badgeBorder: 'border-green-200 dark:border-green-800',
        battleBg: 'bg-green-50 dark:bg-green-900/20',
        battleBorder: 'border-green-100 dark:border-green-800/50',
        battleText: 'text-green-700 dark:text-green-400',
        battleCountBg: 'bg-green-600 text-white border-transparent'
    },
    'JASONS': {
        indexCard: 'border-emerald-300 bg-emerald-100/40 dark:border-emerald-900/50 dark:bg-emerald-900/20',
        indexText: 'text-emerald-800 dark:text-emerald-400',
        badgeBg: 'bg-emerald-50 dark:bg-emerald-900/20',
        badgeText: 'text-emerald-700 dark:text-emerald-400',
        badgeBorder: 'border-emerald-200 dark:border-emerald-800',
        battleBg: 'bg-emerald-50 dark:bg-emerald-900/20',
        battleBorder: 'border-emerald-100 dark:border-emerald-800/50',
        battleText: 'text-emerald-700 dark:text-emerald-400',
        battleCountBg: 'bg-emerald-600 text-white border-transparent'
    },
    'MARKETPLACE': {
        indexCard: 'border-emerald-300 bg-emerald-100/40 dark:border-emerald-900/50 dark:bg-emerald-900/20',
        indexText: 'text-emerald-800 dark:text-emerald-400',
        badgeBg: 'bg-emerald-50 dark:bg-emerald-900/20',
        badgeText: 'text-emerald-700 dark:text-emerald-400',
        badgeBorder: 'border-emerald-200 dark:border-emerald-800',
        battleBg: 'bg-emerald-50 dark:bg-emerald-900/20',
        battleBorder: 'border-emerald-100 dark:border-emerald-800/50',
        battleText: 'text-emerald-700 dark:text-emerald-400',
        battleCountBg: 'bg-emerald-600 text-white border-transparent'
    },
    'MANNINGS': {
        indexCard: 'border-orange-300 bg-orange-50/50 dark:border-orange-900/50 dark:bg-orange-900/20',
        indexText: 'text-orange-500 dark:text-orange-400 drop-shadow-sm',
        badgeBg: 'bg-orange-100 dark:bg-orange-900/30',
        badgeText: 'text-orange-500 dark:text-orange-400 drop-shadow-sm',
        badgeBorder: 'border-orange-400 dark:border-orange-700',
        battleBg: 'bg-orange-50 dark:bg-orange-900/20',
        battleBorder: 'border-orange-200 dark:border-orange-800/50',
        battleText: 'text-orange-500 dark:text-orange-400 drop-shadow-sm',
        battleCountBg: 'bg-orange-500 text-white border-transparent shadow-sm'
    },
    'AEON': {
        indexCard: 'border-fuchsia-200 bg-fuchsia-50/30 dark:border-fuchsia-900/50 dark:bg-fuchsia-900/20',
        indexText: 'text-fuchsia-700 dark:text-fuchsia-400',
        badgeBg: 'bg-fuchsia-50 dark:bg-fuchsia-900/20',
        badgeText: 'text-fuchsia-600 dark:text-fuchsia-400',
        badgeBorder: 'border-fuchsia-200 dark:border-fuchsia-800',
        battleBg: 'bg-fuchsia-50 dark:bg-fuchsia-900/20',
        battleBorder: 'border-fuchsia-100 dark:border-fuchsia-800/50',
        battleText: 'text-fuchsia-700 dark:text-fuchsia-400',
        battleCountBg: 'bg-fuchsia-600 text-white border-transparent'
    },
    'SASA': {
        indexCard: 'border-pink-200 bg-pink-50/30 dark:border-pink-900/50 dark:bg-pink-900/20',
        indexText: 'text-pink-700 dark:text-pink-400',
        badgeBg: 'bg-pink-50 dark:bg-pink-900/20',
        badgeText: 'text-pink-600 dark:text-pink-400',
        badgeBorder: 'border-pink-200 dark:border-pink-800',
        battleBg: 'bg-pink-50 dark:bg-pink-900/20',
        battleBorder: 'border-pink-100 dark:border-pink-800/50',
        battleText: 'text-pink-700 dark:text-pink-400',
        battleCountBg: 'bg-pink-600 text-white border-transparent'
    },
    'DCHFOOD': {
        indexCard: 'border-yellow-300 bg-yellow-50/50 dark:border-yellow-900/50 dark:bg-yellow-900/20',
        indexText: 'text-yellow-500 dark:text-yellow-400 drop-shadow-sm',
        badgeBg: 'bg-yellow-100 dark:bg-yellow-900/30',
        badgeText: 'text-yellow-500 dark:text-yellow-400 drop-shadow-sm',
        badgeBorder: 'border-yellow-400 dark:border-yellow-700',
        battleBg: 'bg-yellow-50 dark:bg-yellow-900/20',
        battleBorder: 'border-yellow-200 dark:border-yellow-800/50',
        battleText: 'text-yellow-500 dark:text-yellow-400 drop-shadow-sm',
        battleCountBg: 'bg-yellow-400 text-slate-900 border border-yellow-500 shadow-sm'
    },
    'DEFAULT': {
        indexCard: 'border-slate-100 bg-slate-50/50 dark:border-slate-700 dark:bg-slate-700/30',
        indexText: 'text-slate-600 dark:text-slate-300',
        badgeBg: 'bg-slate-100 dark:bg-slate-700',
        badgeText: 'text-slate-600 dark:text-slate-300',
        badgeBorder: 'border-slate-200 dark:border-slate-600',
        battleBg: 'bg-slate-50 dark:bg-slate-900/20',
        battleBorder: 'border-slate-100 dark:border-slate-800/50',
        battleText: 'text-slate-700 dark:text-slate-400',
        battleCountBg: 'bg-slate-600 text-white border-transparent'
    }
};

window.categoryDict = window.categoryDict || {};
window.categoryDict['en'] = {
    '飲品': 'Beverages',
    '米 / 食油 / 罐頭 / 蔬果 / 肉類': 'Rice / Oil / Canned / Veg / Meat',
    '家居用品 / 寵物食品及用品': 'Household / Pet Supplies',
    '粉麵 / 煮食用料 / 冷凍加工食品': 'Noodles / Cooking / Frozen',
    '奶類及乳製品 / 大豆製品 / 蛋類': 'Dairy / Soy / Eggs',
    '糖果 / 餅乾 / 小食': 'Snacks / Biscuits / Candies',
    '麵包蛋糕 / 穀類早餐 / 麵包醬': 'Bakery / Cereal / Spreads',
    '酒類': 'Alcohol',
    '個人護理': 'Personal Care',
    '奶粉 / 嬰兒用品': 'Baby Powder / Supplies'
};